#output: TestException
#output: test

import testsupport.TestException;

try {
	throw new TestException("test");
} catch ex {
	println(typeof(ex));
	println(ex.message);
}
